### ISSUE TITLE
docker.sock permission denied on OpenShift

### ISSUE THREAD

**Issue by dacleyra** [appsody/tekton-example#16]
Openshift 3.11

Service account is configured as

```
oc apply -n kabanero -f https://raw.githubusercontent.com/appsody/tekton-example/master/appsody-service-account.yaml
oc adm policy add-cluster-role-to-user cluster-admin -z appsody-sa -n kabanero
oc adm policy add-scc-to-user hostmount-anyuid -z appsody-sa -n kabanero
oc policy add-role-to-user system:image-builder system:serviceaccount:kabanero:appsody-sa
```

In one case, this is enough for build-task assemble-extract-step to access /var/run/docker.sock

In another case, access to docker.sock is denied until the following is added to build-task
```
  steps:
    - name: assemble-extract-step
      securityContext:
        privileged: true
```

Related
https://danwalsh.livejournal.com/78373.html

The first case is an olded cluster, with some older selinux policy modules
Either there was a security hole in case #1, or scc is not applying in case #2? not quite sure

**Comment by dacleyra** [comment]
appears to be a timing issue between when SCC is created and build task is created.

maybe worth a troubleshooting note

**Comment by dacleyra** [comment]
The root cause is this issue

https://github.com/tektoncd/pipeline/issues/1103

**Comment by neeraj-laad** [comment]
We would like to do this work as part of https://github.com/appsody/appsody/issues/96. Closing this issue.
