### ISSUE TITLE
Serviceability: build-step modify-yaml & install-knative should print if YAMLFILE not found

### ISSUE THREAD

**Issue by dacleyra** [appsody/tekton-example#19]
Since the YAMLFILE is user configurable, if the task stages can not find this file, it should print a useful message to let the user know.

**Comment by mhamwala** [comment]
Thanks for raising this issue @dacleyra!

cc: @chilanti

**Comment by neeraj-laad** [comment]
@EnriqueL8 Will this be addressed or invalid with the changes you are making to the tekton-example as part of #27 ?

**Comment by neeraj-laad** [comment]
Closing this as pipelines no longer assume that the yaml is present and instead use appsody build.
