### ISSUE TITLE
install manifest task fail

### ISSUE THREAD

**Issue by qibobo** [appsody/tekton-example#22]
I tried the example on my minishift but the last task are always failed with the message:

`error: unable to recognize "/workspace/git-source/app-deploy.yaml": no matches for kind "AppsodyApplication" in version "appsody.dev/v1beta1`

My appsody app repo: https://github.com/qibobo/appsody-node/blob/master/app-deploy.yaml

**Comment by kylegc** [comment]
@chilanti any thoughts on this?

**Comment by chilanti** [comment]
@qibobo - please try to install the `appsody operator` on your cluster first, and let me know if that makes a difference. Things have changed recently in the way `app-deploy.yaml` is generated and it could be that the pipeline is broken.
Try out:
```
appsody operator install -n <namespace>
```
where <namespace> is the namespace where the app should be installed. Thanks.

**Comment by neeraj-laad** [comment]
@qibobo Are you able to try out the steps suggested above?

**Comment by qibobo** [comment]
@chilanti thank you.

**Comment by brightzheng100** [comment]
I realized that we have to run `appsody operator install -n <namespace>` in each namespace where I want to deploy `appsody` applications to.

Is it by design (by consideration of security, for example)?
