### ISSUE TITLE
failed to apply pipeline run

### ISSUE THREAD

**Issue by qibobo** [appsody/tekton-example#23]
I follow the guide but in the last step it failed to create a pipeline run:

```
kubectl apply -f appsody-pipeline-run.yaml
Error from server (InternalError): error when creating "appsody-pipeline-run.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "trigger"
```

**Comment by kylegc** [comment]
@chilanti any thoughts on this?

**Comment by chilanti** [comment]
@qibobo  - what version of Knative/Istio are you working with? This sounds like a version mismatch issue.

**Comment by neeraj-laad** [comment]
@qibobo Please, can you provide the information requested above?

**Comment by qibobo** [comment]
both istio and knative are v0.4.0 introduced by https://knative.dev/v0.4-docs/install/knative-with-iks/

**Comment by chilanti** [comment]
@qibobo - It looks like something changed between tekton 0.5.x and 0.7.0... I'll do some additional investigation and possibly update the yaml.
