### ISSUE TITLE
can not mount docker.sock in step assemble-extract-step

### ISSUE THREAD

**Issue by qibobo** [appsody/tekton-example#24]
I installed the example in a IBM kubernetes cluster and when tried to run the task, the error below showed:
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"docker inspect" requires at least 1 argument.See 'docker inspect --help'.Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]Return low-level information on Docker objects`
While in minishift there is a step for allowing appsody-sa to mount docker.sock, does in other kubernetes cluster also need this?
`oc adm policy add-scc-to-user hostmount-anyuid -z appsody-sa`

**Comment by chilanti** [comment]
@qibobo - yes - this is why we have documented that step in the readme of the tekton example repo under Openshift Considerations. I am closing this issue - please reopen if appropriate.
