### ISSUE TITLE
When trying this on OCP 4.2 I get errors with docker.sock

### ISSUE THREAD

**Issue by airazabal** [appsody/tekton-example#28]
so I was able to create and run the pipeline in the repo with my code, however when the pipeline runs, I get this message:
Pappsody-manual-pipeline-run2-r-vs7kh-appsody-build-rfsxs-pod-71a519NamespaceNSdefault
less than a minute ago
Generated from kubelet on worker3
3 times in the last 5 minutes
Unable to mount volumes for pod "appsody-manual-pipeline-run2-r-vs7kh-appsody-build-rfsxs-pod-71a519_default(2dba0784-070a-11ea-b5b5-005056a587f1)": timeout expired waiting for volumes to attach or mount for pod "default"/"appsody-manual-pipeline-run2-r-vs7kh-appsody-build-rfsxs-pod-71a519". list of unmounted volumes=[docker-socket]. list of unattached volumes=[docker-socket appsody-manual-pipeline-run2-r-vs7kh-pvc tools downward workspace home secret-volume-regcred-xb96v secret-volume-appsody-sa-dockercfg-dnbf7-w92sk appsody-sa-token-xt8fp]
PodPappsody-manual-pipeline-run2-r-vs7kh-appsody-build-rfsxs-pod-71a519NamespaceNSdefault
less than a minute ago
Generated from kubelet on worker3
11 times in the last 7 minutes
MountVolume.SetUp failed for volume "docker-socket" : hostPath type check failed: /var/run/docker.sock is not a socket file

Looks like docker is not running on the image???

**Comment by chilanti** [comment]
This is a known issue unfortunately. On OCP 4.2, sharing the `docker.sock` isn't an option. We are going to convert this example to use `buildah` as soon as we can.

**Comment by brightzheng100** [comment]
I have the same issue while running in [`kind`](https://github.com/kubernetes-sigs/kind):

```
Warning  FailedMount       42s (x14 over 13m)   kubelet, my-cluster-worker3  MountVolume.SetUp failed for volume "docker-socket" : hostPath type check failed: /var/run/docker.sock is not a socket file
```

**Comment by neeraj-laad** [comment]
This will be addressed in https://app.zenhub.com/workspaces/appsody-zenhub-5d15215ee0945f63bfe31734/issues/appsody/tekton-example/27

Closing this as a duplicate
