### ISSUE TITLE
For OCP, the storageClassName attribute is required. 

### ISSUE THREAD

**Issue by airazabal** [appsody/tekton-example#29]
the sample okd-pv.yaml did not have this and the pipeline never starts since it can not bind to the PV. Here is mine that worked:
apiVersion: v1
kind: PersistentVolume
metadata:
 name: appsody-manual-pipeline-run2-pvc
 namespace: default
spec:
 capacity:
   storage: 5Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /var/lib/appsody-manual-pipeline-run-pvc
 storageClassName: non-dynamic

**Comment by neeraj-laad** [comment]
@EnriqueL8 Please can you check if this is now resolved as we have completely refactored the tekton example.

**Comment by EnriqueL8** [comment]
Last time I ran this pipeline, I didn't need to add that `storageClassName`

**Comment by neeraj-laad** [comment]
@airazabal please can you provide more information on your environment setup, so we can try to reproduce this issue.

**Comment by neeraj-laad** [comment]
closing due to lack of information. Please reopen if this is still an issue.
