### ISSUE TITLE
java-microprofile YAMLFILE appsody-service.yaml is not found in expected location

### ISSUE THREAD

**Issue by dacleyra** [appsody/tekton-example#7]
The appsody-build-task runs the following container
For java microprofile the YAMLFILE appsody-service.yaml is not found under `/workspace/extracted` it is found under `/workspace/appsody-source`

```
    - name: install-knative
      image: lachlanevenson/k8s-kubectl
      command: ['/bin/sh']
      args: ['-c', 'find /workspace/extracted -name ${YAMLFILE} -type f|xargs kubectl apply -f ; sleep 3600']
```

**Comment by chilanti** [comment]
Short term, we will change that `find` command to point to `/workspace/appsody-source`. The reason why the pipeline doesn't find it in this case is that the Java stack mounts only certain elements of the project "root" directory (`pom.xml` and the `src` directory). The `extract` step of the pipeline - therefore - fails to extract the `appsody-service.yaml`, if it isn't under `src`.

**Comment by neeraj-laad** [comment]
This has been fixed using the current work around  in https://github.com/appsody/tekton-example/pull/8

**Comment by neeraj-laad** [comment]
@chilanti I have merged the PR to update the documentation to reflect this additional configuration.

@dacleyra Can you please confirm that the documentation is not accurate to make this work with OpenShift. Given, this is just an example to show integration with tekton. I'd like to close this issue and just have the additional steps documented. 

When we have proper integration with Tekton and other CI systems, we might consider providing more out-of-the-box experience.

I'm closing this issue based on this comment. Please re-open if you believe, we can do more on this.
